version: '3.4'

services:
  catan:
    image: ${DOCKER_REGISTRY}catan
    build:
      context: .
      dockerfile: Catan/Dockerfile
    ports: 
      - "80:80"
    depends_on:
      - db
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
     