version: '3.4'

services:     
  catan:
    container_name: 'catan'
    image: '${DOCKER_REGISTRY}catan'
    build:
      context: .
      dockerfile: Catan/Dockerfile
    volumes:
      - .:/var/www/aspnetcoreapp
    ports:
     - "5000:5000"
    depends_on:
     - "postgres"
    networks:
      - aspnet-network

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - aspnet-network

networks:
  aspnetcoreapp-network:
    driver: bridge
